### ISSUE TITLE
for и префиксы

### ISSUE THREAD

**Issue by HawkeyePierce89** [kisenka/posthtml-rename-id#1]
Проблема, когда у нас префиксуется id у инпута, но при этом у label остаётся старый for

Нужно
1) Опция, чтобы указывать нужно ли нам префиксовать for, не знаю, наверное всё-таки в true её ставить по умолчанию
2) Собственно префиксование for на основе опции

**Comment by kisenka** [comment]
@HawkeyePierce89 done, please check `posthtml-rename-id@1.0.3`.

**Comment by HawkeyePierce89** [comment]
Работает, спасибо
